version: '3.8'

services:
  identity-api:
    build:
      context: .
      dockerfile: Zeladoria.Identity.API/Dockerfile
    environment:
      # Puxa os valores diretamente do arquivo .env
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Jwt__Key=${JWT_KEY}

  ocorrencias-api:
    build:
      context: .
      dockerfile: Zeladoria.Ocorrencias.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Jwt__Key=${JWT_KEY}

  gateway-api:
    build:
      context: .
      dockerfile: Zeladoria.Gateway.API/Dockerfile
    environment:
      - ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address=http://identity-api:8080
      - ReverseProxy__Clusters__ocorrencias-cluster__Destinations__destination1__Address=http://ocorrencias-api:8080
    ports:
      - "9000:8080" 
    depends_on:
      - identity-api
      - ocorrencias-api